version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./database:/usr/src/app/database
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    env_file:
      - .env
