version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      #- ./backup:/usr/src/app/backup
      - ./config/ssl/ca-cert.pem:/usr/src/app/ssl/ca-cert.pem
      - ./config/ssl/client-cert.pem:/usr/src/app/ssl/client-cert.pem
      - ./config/ssl/client-key.pem:/usr/src/app/ssl/client-key.pem
    environment:
      - SESSION_TIMEOUT=30
      - MIN_PASSWORD_LENGTH=10
    env_file:
      - .env
    depends_on:
      - redis
      - mariadb  # Ensure the web service starts after MariaDB is ready
    networks:
      - pylockr-network

  scheduler:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_Scheduler
    volumes:
      - ./backup:/usr/src/app/backup
      - ./config/ssl/ca-cert.pem:/usr/src/app/ssl/ca-cert.pem
      - ./config/ssl/client-cert.pem:/usr/src/app/ssl/client-cert.pem
      - ./config/ssl/client-key.pem:/usr/src/app/ssl/client-key.pem
    environment:
      - BACKUP_DIR=/usr/src/app/backup
      - MAX_DB_BACKUPS=42
      - BACKUP_FREQUENCY=240
      - RUN_SCHEDULER=true
    env_file:
      - .env
    depends_on:
      - redis
      - mariadb  # Ensure the scheduler service starts after MariaDB is ready
    networks:
      - pylockr-network

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - pylockr-network

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=pylockrdb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./config/cnf:/etc/mysql/conf.d  # Custom my.cnf
      - ./config/keys:/etc/mysql/encryption  # Data at Rest Encryption key
      - ./config/ssl/server-cert.pem:/etc/mysql/ssl/server-cert.pem
      - ./config/ssl/server-key.pem:/etc/mysql/ssl/server-key.pem
      - ./config/ssl/ca-cert.pem:/etc/mysql/ssl/ca-cert.pem

    networks:
      - pylockr-network

networks:
  pylockr-network:
    driver: bridge

volumes:
  mariadb_data: {}
