version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./database:/usr/src/app/database
      - ./backup:/usr/src/app/backup
    environment:
      - BACKUP_DIR=/usr/src/app/backup
      - DB_PATH=/usr/src/app/database
      - SESSION_TIMEOUT=30
      - MIN_PASSWORD_LENGTH=10
    env_file:
      - .env
    depends_on:
      - redis  # Ensure the web service starts after Redis
    networks:
      - pylockr-network

  scheduler:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_Scheduler
    volumes:
      - ./database:/usr/src/app/database
      - ./backup:/usr/src/app/backup
    environment:
      - BACKUP_DIR=/usr/src/app/backup
      - DB_PATH=/usr/src/app/database
      - MAX_DB_BACKUPS=42
      - BACKUP_FREQUENCY=240
      - RUN_SCHEDULER=true
      - SQLCIPHER_KEY=${SQLCIPHER_KEY}
    depends_on:
      - redis  # Ensure the scheduler service starts after Redis
    networks:
      - pylockr-network

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - pylockr-network

networks:
  pylockr-network:
    driver: bridge
