version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./database:/usr/src/app/database
      - ./backup:/usr/src/app/backup
    environment:
      - BACKUP_DIR=/usr/src/app/backup
      - DB_PATH=/usr/src/app/database
      - SESSION_TIMEOUT=30
      - MIN_PASSWORD_LENGTH=12
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    depends_on:
      - redis  # Ensure the web service starts after Redis

  scheduler:
    build: .
    volumes:
      - ./database:/usr/src/app/database
      - ./backup:/usr/src/app/backup
    environment:
      - MAX_DB_BACKUPS=42
      - BACKUP_FREQUENCY=240
      - RUN_SCHEDULER=true
    env_file:
      - .env
    entrypoint: ./scheduler_entry.sh
    depends_on:
      - redis  # Ensure the scheduler service starts after Redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
