FROM python:3.11

# Install system dependencies required for mariadb
RUN apt-get update && apt-get install -y --no-install-recommends \
    mariadb-client \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' appuser

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the application code into the container
COPY ./app/utils/scheduler.py /usr/src/app/app/utils/scheduler.py
COPY ./app/utils/pylockr_logging.py /usr/src/app/app/utils/pylockr_logging.py
COPY ./scheduler_entry.sh /usr/src/app/

# Install any needed packages specified in requirements.txt
RUN pip install APScheduler 

# Specify the entrypoint script
ENTRYPOINT ["./scheduler_entry.sh"]
